version: "3.5"

services:
  web:
    build: src/
    container_name: zgl
    hostname: zgl
    volumes:
      - ./src:/src
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: "app/app.py"
    tty: true
    stdin_open: true
