version: "3.5"

services:
  web:
    build: src/
    container_name: zgl
    hostname: zgl
    volumes:
      - ./src:/src
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: "app/app.py"
    tty: true
    stdin_open: true
    networks:
      - zgl-network

  db:
    image: mysql:5.7
    container_name: mysql
    hostname: zgl
    env_file:
      - ./db/.env
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/init_query:/docker-entrypoint-initdb.d
      - zgl-db-data:/var/lib/mysql
    ports:
      - 3306:3306 
    networks:
      - zgl-network

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    hostname: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - zgl-network

volumes:
  zgl-db-data:

networks:
  zgl-network:
    driver: bridge
